[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/create-school-signup-checkout"
  to = "/.netlify/functions/create-school-signup-checkout"
  status = 200

[[redirects]]
  from = "/api/stripe-webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200
